---
title: "R Cheat Sheet"
author: "Adele"
date: "2023-11-03"
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
---

# 基础统计学概念

## 常见的统计量

用于帮助我们理解数据的特点，可以得到数据集的一个很好的概述，了解数据的分布和中心趋势

1. **最小值 (Min)**：
   - 这是数据集中最小的数值。
   - 例如，在一个包含 2, 4, 7, 9 的数据集中，最小值是 2。

2. **下四分位数 (Quantile 1) 或 25th 百分位数**：
   - 也称为第一四分位数，它是将数据集分为四等分后的第一个切点。
   - 例如，在一个包含 1, 2, 3, 4, 5, 6, 7, 8 的数据集中，Q1 的值是 2.75 (25% 的数据小于或等于这个数值)。

3. **中位数 (Median) 或 Quantile 2**：
   - 中位数是将数据集从中间分开的值，一半的数据值位于中位数的左边，另一半位于右边。
   - 如果数据集的数量是奇数，则中位数就是中间的数；如果是偶数，则中位数是中间两个数的平均值。
   - 例如，在一个包含 3, 5, 7, 9 的数据集中，中位数是 6。

4. **平均数 (Mean)**：
   - 平均数是所有数据值的总和除以数据值的数量。
   - 例如，在一个包含 2, 3, 4, 5 的数据集中，平均数是 (2+3+4+5) / 4 = 3.5。

5. **上四分位数 (Quantile 3) 或 75th 百分位数**：
   - 也称为第三四分位数，它是将数据集分为四等分后的第三个切点。
   - 例如，在一个包含 1, 2, 3, 4, 5, 6, 7, 8 的数据集中，Q3 的值是 5.25 (75% 的数据小于或等于这个数值)。

6. **最大值 (Max)**：
   - 这是数据集中最大的数值。
   - 例如，在一个包含 2, 4, 7, 9 的数据集中，最大值是 9。

7. **频数 (Frequency)**:
   - 例如，在一个数据集{1, 2, 2, 3, 3, 3, 4}中，数字3的频数是3，因为它出现了三次。

8. **频率 (Relative Frequency)**:
   - 在同一个数据集{1, 2, 2, 3, 3, 3, 4}中，数字3的频率是3/7 ≈ 0.43，因为它出现了三次，总的数据点数量是7。

9. **标准差 (Standard Deviation, SD)**:
   - 在数据集{2, 4, 4, 4, 5, 5, 7, 9}中，标准差是2，这意味着数据点离平均值的平均距离是2。

10. **方差 (Variance)**:
    - 在同一个数据集{2, 4, 4, 4, 5, 5, 7, 9}中，方差是4，因为标准差的平方是2^2 = 4。

11. **范围 (Range)**:
    - 在数据集{2, 4, 7, 9}中，范围是7，因为最大值9减最小值2等于7。

12. **众数 (Mode)**:
    - 在数据集{1, 2, 2, 3, 3, 3, 4}中，众数是3，因为3出现的次数最多。

13. **偏度 (Skewness)**:
    - 如果我们有一个数据集{1, 2, 2, 3, 3, 3, 4}，它的偏度是0，因为数据是对称分布的。

14. **峰度 (Kurtosis)**:
    - 在一个尖峰分布的数据集中，峰度会高于正态分布的峰度。例如，数据集{1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4}的峰度较高，因为数据集的尾部较重。

15. **百分位数 (Percentile)**:
    - 在数据集{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}中，第25个百分位数是3.25，因为25%的数据小于或等于这个值。

16. **相关系数 (Correlation Coefficient)**:
    - 如果我们有两组数据，比如{1, 2, 3, 4, 5}和{2, 4, 6, 8, 10}，它们之间的相关系数是1，因为它们之间存在完全的正线性关系。

17. **回归分析 (Regression Analysis)**:
    - 例如，我们想预测房价基于房子的大小。通过回归分析，我们可以得到一个方程，用来预测基于房子大小的房价。

18. **样本 (Sample)**:
    - 如果我们有一个包含1000个人的大型社区，我们可能只从中抽取100个人来研究他们的收入水平，这100个人就是一个样本。

19. **总体 (Population)**:
    - 在上述例子中，这个社区的所有1000个人就是总体。

